// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables for security and deployment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nqmwughoffvmwscihleu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbXd1Z2hvZmZ2bXdzY2lobGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NTAxNTUsImV4cCI6MjA4MzUyNjE1NX0.K0CAbQbJq4NV7MnokaHiKQx6Fs_JrdWvKPXMEOyml74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);